### ISSUE TITLE
Readme file should be improved

### ISSUE THREAD

**Issue by Ritu-2001** [mrsparkle-70/Emotion-detection-using-JS#1]

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by Code1705** [comment]
I will definately want to make a fresh Readme file , please assign me this issue under JWOC.

**Comment by purbakundu** [comment]
i want to contribute

**Comment by mrsparkle-70** [comment]
@Atul-8115 u r assigned this issue

**Comment by Shreyan-12345** [comment]
@mrsparkle-70 I want to work under JWOC is it is not solved
