### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by ritika728** [mrsparkle-70/Emotion-detection-using-JS#101]
Hey @mrsparkle-70, I would like to open this issue under JWOC. 

A frequently asked questions section is a very crucial part of any website. A wish to add this page where the user can get answers to the following questions: 
- What is the website all about
- What are its features
- What all technologies do it use
- How is it better then other apps
-and etc. 

I'll make it responsive & will add it in navbar of all the pages. Kindly assign

**Comment by mrsparkle-70** [comment]
Sure
