### ISSUE TITLE
Add project admin and contributors page

### ISSUE THREAD

**Issue by ritika728** [mrsparkle-70/Emotion-detection-using-JS#107]
Hey @mrsparkle-70, I wish to open this issue under JWOC. I wish to add a animated & responsive section of project admin and contributors in the website. Kindly assign. 
And let me know whether I should form a new page or I should add this section in the contact us page. Thank you!

**Comment by mrsparkle-70** [comment]
We can do it after JWOC

Now we should focus only on extra features what we can provide

**Comment by ritika728** [comment]
Okay!
