### ISSUE TITLE
Want to add some documentation

### ISSUE THREAD

**Issue by Sowham-3098** [mrsparkle-70/Emotion-detection-using-JS#11]
I will be adding a LICENSE file and Contributing.md 
and also the contributor's list in README.md.

**Comment by Sowham-3098** [comment]
@mrsparkle-70 please assign me this issue under JWOC.

**Comment by Yogeshkarma** [comment]
I want to work under JWOC

**Comment by mrsparkle-70** [comment]
This project is not accepting anymore contributions on documentation
