### ISSUE TITLE
[Enhancement] Migrate to EJS Template Engine for Backend

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#111]
# Description 
## EJS Benefit : 
 - EJS was so similar to HTML so I found it easy.
- EJS uses all the JS jargon and logic, so if you are proficient in JS, you can use EJS right away.
- EJS is way faster than Jade and handlebars.
- EJS has a really smart error handling mechanism built right into it. It points out to you, the line numbers on which an error has occurred so that you don’t end up looking through the whole template file wasting your time in searching for bugs.
- Simple template tags: <% %>.
- Custom delimiters (e.g., use <? ?> instead of <% %>)

## Assign me this issue under JWOC 2023. @mrsparkle-70 😄

**Comment by pooranjoyb** [comment]
Routing will be much efficient after implementation of `view-engine` as `ejs` in the backend. @mrsparkle-70

**Comment by pooranjoyb** [comment]
Hey @mrsparkle-70 , I would be grateful if you revise the difficulty level of this issue as migrating to EJS is a real hardship and  time consuming. Also I have to update the routing of each & every links in the website in its backend. Would be glad if you'd update the difficulty level.

**Comment by mrsparkle-70** [comment]
Ok sure

**Comment by mrsparkle-70** [comment]
What should be the path then ?

**Comment by mrsparkle-70** [comment]
Can you help me with that

**Comment by pooranjoyb** [comment]
Okay, So similar to what you did while you updated the target to backend file. The path to the backend should be `./backend/server.js` @mrsparkle-70 Try, and lemme know if it works, if not we will fix it. Even after the event ends we will be working on it.

**Comment by mrsparkle-70** [comment]
[image: image.png]
It asks here the root Directory

**Comment by pooranjoyb** [comment]
I cannot see the image. Try uploading it again 😞

**Comment by mrsparkle-70** [comment]
Check in mail
Not at Github

**Comment by pooranjoyb** [comment]
Let's Chat in Discord.
