### ISSUE TITLE
Make a small input form which takes name age gender as input below the live video.

### ISSUE THREAD

**Issue by mrsparkle-70** [mrsparkle-70/Emotion-detection-using-JS#13]

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by mrsparkle-70** [comment]
Make one

**Comment by vk20july** [comment]
one input form which takes all the information i.e name,age,gender right?

**Comment by mrsparkle-70** [comment]
Yes

**Comment by vk20july** [comment]
ok sir

**Comment by mrsparkle-70** [comment]
@vk20july any update ?

**Comment by manya0210** [comment]
Hello sir.. I want to work on this issue under jwoc

**Comment by vk20july** [comment]
@mrsparkle-70 sir working on it 
currently figuring out the CSS of this input form
Max to max it will complete within 2 days

**Comment by vk20july** [comment]
@mrsparkle-70 90% is done will give you the full detail by tomorrow evening

**Comment by vk20july** [comment]
Made a PR
check the latest commit

**Comment by mrsparkle-70** [comment]
There are some merge conflicts
Check again and make pr

**Comment by pooranjoyb** [comment]
I would like to work on this issue. But I would really love to know what will actually happen if we take user input below the emotion detector? I would like to know the outcome after adding the form. @mrsparkle-70

**Comment by mrsparkle-70** [comment]
Actually I am planning to create a database in some form ... It is not
planned fully till now

**Comment by pooranjoyb** [comment]
Ok, so do you want me to create this form as of now? Or you're planning something more in PHASE 2 ? @mrsparkle-70

**Comment by mrsparkle-70** [comment]
As Phase 2 begins today
U can decide first which database will be suitable for this

**Comment by pooranjoyb** [comment]
We can use either MongoDB or MySql as a database but for this we need to convert the full application into a NodeJS application with various endpoints functioning differently. 
Let me know what are your thoughts and what to do with the `name`, `gender` of the user by storing in the DB?
@mrsparkle-70

**Comment by mrsparkle-70** [comment]
MongoDB would be great
And we can just store emotion and age
Just these two for the time being

This data will be used for machine Learning models for age vs emotion
analysis

**Comment by pooranjoyb** [comment]
Cool, but initially I would raise an issue (after the current issue is completed) to make this whole application a `NodeJS` App. 
Then we'll continue adding more enhancements. 😄 @mrsparkle-70

**Comment by mrsparkle-70** [comment]
Sure

**Comment by pooranjoyb** [comment]
You can assign me this issue now. I can start working as the NodeJS config is done. :) @mrsparkle-70

**Comment by mrsparkle-70** [comment]
Yes you can start
