### ISSUE TITLE
Design the background

### ISSUE THREAD

**Issue by Shreyan-12345** [mrsparkle-70/Emotion-detection-using-JS#14]
@mrsparkle-70  pls assign me this under JWOC

**Comment by mrsparkle-70** [comment]
@Shreyan-12345 any update ?

**Comment by pooranjoyb** [comment]
@mrsparkle-70 Can I start working in this issue as there's isn't any update? 
I want to work on this issue under JGEC Winter of Code.
If you want me to design only the background it will take a day only but I really would love to improve the main UI of the webpage. I might be using frameworks like Bootstrap or Tailwind for UI. 
Please label it as **medium** issue.

**Comment by mrsparkle-70** [comment]
Yes
U can start
I will assign u when I am free

**Comment by pooranjoyb** [comment]
Thank you @mrsparkle-70

**Comment by Shreyan-12345** [comment]
@mrsparkle-70 I will give PR by today pls don't assign anyone

**Comment by pooranjoyb** [comment]
> @mrsparkle-70 I will give PR by today pls don't assign anyone

Sure brother, would be happy to see your contribution. Let's not rush :smile: 💯

**Comment by Shreyan-12345** [comment]
@mrsparkle-70 I have made the PR pls merge it

**Comment by Shreyan-12345** [comment]
@mrsparkle-70 is it merged?
