### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by Laxmankohar** [mrsparkle-70/Emotion-detection-using-JS#17]
Hey @mrsparkle-70 , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by Laxmankohar** [comment]
Do you have a logo with you ? please do share it otherwise select from given image sothat i can add it


![emotions](https://user-images.githubusercontent.com/73365025/219433624-3364e280-691b-45bc-95a3-2cd1c8e81a76.png)
![emotion](https://user-images.githubusercontent.com/73365025/219433604-9ba5a383-cffe-4a2b-9b45-b459ef15a78f.png)

**Comment by mrsparkle-70** [comment]
U need to design it yourself from scratch

**Comment by mrsparkle-70** [comment]
Completely your creativity

**Comment by Keshab1113** [comment]
I want to add an amazing favicon for this Web-Site, I select an Emotional favicon for your Web, Please assign me for this issue.
#jwoc
#JGEC

**Comment by deepbeatz** [comment]
I want to work on this under JWOC
