### ISSUE TITLE
Add an option for uploading an image to detect faces in it.

### ISSUE THREAD

**Issue by ayushanand308** [mrsparkle-70/Emotion-detection-using-JS#19]
Add method to the index.html and the functionality for it to the JS file.

**Comment by ayushanand308** [comment]
@mrsparkle-70 Please assign me this under JWOC

**Comment by mrsparkle-70** [comment]
@ayushanand308 any update ?

**Comment by LuckySingh9897** [comment]
Please assign this issue to me under JWOC

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by Aditya-Raghuvanshi** [comment]
i want to work on this issue under JWOC.

**Comment by ayushanand308** [comment]
@mrsparkle-70 I was busy with another issue. I will be submitting the code today.

**Comment by mrsparkle-70** [comment]
Ok

**Comment by ayushanand308** [comment]
![image](https://user-images.githubusercontent.com/99035102/220208439-4f240c3b-02e8-4927-abf7-1466db8fff0c.png)

**Comment by ayushanand308** [comment]
Its almost done. Just few adjustments and I will be pushing the code soon.

**Comment by ayushanand308** [comment]
I submitted a PR. Please review it @mrsparkle-70
