### ISSUE TITLE
Add a nice navbar 

### ISSUE THREAD

**Issue by mrsparkle-70** [mrsparkle-70/Emotion-detection-using-JS#2]

**Comment by Arceus-sj** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by mrsparkle-70** [comment]
Sure
I will assign it once the coding period starts.

Regards,
Subham Sinha
Mentor
JWOC

**Comment by Shantanu-Meta** [comment]
I would like to contribute in this project to grow to features more under JWOC. If you wish you can assign me.

**Comment by KrunalGupta02** [comment]
i would like to work on it

**Comment by mrsparkle-70** [comment]
The one who comments after 12 will be assigned

**Comment by manya0210** [comment]
Hello sir ..I want to contribute to this issue under jwoc

**Comment by Suniti-0020** [comment]
Hi  @mrsparkle-70 
I am interested to work on it.
I have made projects and have an experience in designing different nav bars.
Can you assign it to me .  under JWOC

**Comment by PARASnagpal99** [comment]
I would like to work on this . Please assign this to me .

**Comment by vk20july** [comment]
I want to work on this issue under JWOC
It is fully responsive and nice design

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue, please assign it to me under JWOC.

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by purbakundu** [comment]
i want to contribute

**Comment by mrsparkle-70** [comment]
@Suniti-0020 
I expect good work from u
Lets make a great navbar

**Comment by mrsparkle-70** [comment]
@Suniti-0020 any update with the navbar ?

**Comment by SattyamSamania** [comment]
Hey @mrsparkle-70 I want to work on this issue under JWOC. Kindly assign. Thank you!
