### ISSUE TITLE
Add contributors section in readme file

### ISSUE THREAD

**Issue by Arbtrage** [mrsparkle-70/Emotion-detection-using-JS#21]
I want to add a contributors section in the readme file where all the contributors in this project would be shown.
@mrsparkle-70 , please assign me this issue.

**Comment by mrsparkle-70** [comment]
Sure 
U can start 
I will assign u

**Comment by Arbtrage** [comment]
Okay

**Comment by Arbtrage** [comment]
@mrsparkle-70 , I have completed the work but still haven't been assigned. Please assign me so that I can create a pull request for this issue.

**Comment by mrsparkle-70** [comment]
I will assign this in morning

**Comment by Arbtrage** [comment]
Okay

**Comment by Arbtrage** [comment]
@mrsparkle-70 , please assign me this issue under Jwoc

**Comment by utkarsh006** [comment]
@mrsparkle-70 Assign me the issue under JWOC

**Comment by Keshab1113** [comment]
I want to add a contributors section in the readme file under JWOC, please assign me.

**Comment by vatan-prakash** [comment]
please assign this issue to me
