### ISSUE TITLE
Properly writing and documentation of this whole project in the Readme step by step in as details as possible. 

### ISSUE THREAD

**Issue by mrsparkle-70** [mrsparkle-70/Emotion-detection-using-JS#22]

**Comment by Trisha-tech** [comment]
Hello @mrsparkle-70, I would like to work on this issue under JWOC 2023.

**Comment by mrsparkle-70** [comment]
start

**Comment by mrsparkle-70** [comment]
@Trisha-tech Any update ?

**Comment by Trisha-tech** [comment]
> @Trisha-tech Any update ?

Yes @mrsparkle-70, I have created the Pull Request for the same issue. Kindly check and guide if anything also want to be included. 
Also, currently I am working on the adding "about of the project", "features" and "badges" on the Readme.

**Comment by mrsparkle-70** [comment]
Sure
Create an issue
And will allot accordingly.
