### ISSUE TITLE
I want to add an amazing favicon for this Web-Site

### ISSUE THREAD

**Issue by Keshab1113** [mrsparkle-70/Emotion-detection-using-JS#23]
I want to add an amazing favicon for this Web-Site, I select an Emotional favicon for your Web, Please assign me for this issue. 
#jwoc 
#JGEC

**Comment by LuckySingh9897** [comment]
I want to work on this issue sir under JWOC

**Comment by VaibhavTalkhande** [comment]
Can I work on it

**Comment by mecivil** [comment]
I want to work on this issue under JWOC

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by vatan-prakash** [comment]
please assign this issue to me

**Comment by LuckySingh9897** [comment]
Sir  @mrsparkle-70, I submitted a PR and you have merged it but you have not assigned  so I didn't get any points under JWOC 
please look through it sir [https://github.com/mrsparkle-70/Emotion-detection-using-JS/pull/30#issue-1590397779](URL)
