### ISSUE TITLE
Dark and Light

### ISSUE THREAD

**Issue by Keshab1113** [mrsparkle-70/Emotion-detection-using-JS#28]
I want to add dark and light mood on your web-site, Under JWOC, please assign me for this issue

**Comment by VaibhavTalkhande** [comment]
Can I work on this this issue I know react as well as javascript

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC

**Comment by deepbeatz** [comment]
I want to work on this under JWOC
