### ISSUE TITLE
Distorted Alignment 

### ISSUE THREAD

**Issue by ritika728** [mrsparkle-70/Emotion-detection-using-JS#31]
Hey, I would like to open this issue under JWOC. 
I wish to align this by making a flexbox for the text (switch to light/dark mode) & this toggle button.

![photo](https://user-images.githubusercontent.com/91181981/219881748-33268928-ad0d-4c5b-9b28-74600c6fbd2c.png)

**Comment by mrsparkle-70** [comment]
Sure
