### ISSUE TITLE
Better Folder Restructuring needed

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#39]
## Issues : 
The folder structuring for the project is messed up as the directories are not organized properly.

## FIX : 
- [x] Need to use ```.gitignore``` to ignore some basic static files
- [x] Add a seperate ``src`` directory for the frontend. CSS, JS etc should be inside one ``src`` directory

Would be glad if you assign these issues to me under **JGEC Winter of Code**.  @mrsparkle-70

**Comment by mrsparkle-70** [comment]
Sure
You can start 
I will assign it to you
