### ISSUE TITLE
Create a new CSS file for this project

### ISSUE THREAD

**Issue by sagnik3788** [mrsparkle-70/Emotion-detection-using-JS#4]

**Comment by KrunalGupta02** [comment]
Hi I would like to work on it plz assign to me #jwoc

**Comment by Dinokojt7** [comment]
Hi please assign

**Comment by mrsparkle-70** [comment]
The one who comments after 12 will be assigned to it

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by Sarita-021** [comment]
Hi , @mrsparkle-70  I would like to contribute to the project and have an experience in maintaining code files. 
Can you assign it to me .  under JWOC

**Comment by Code1705** [comment]
I am willing to contribute to make a fresh CSS file for this project , please assign me this issue under JWOC

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue, please assign it to me under JWOC.

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by purbakundu** [comment]
i want to contribute

**Comment by SubhajitB05** [comment]
I want to contribute on this issue under JWOC

**Comment by mrsparkle-70** [comment]
@Sarita-021 
U r assigned this
