### ISSUE TITLE
Add a method to tell whether two given faces are similar or not 

### ISSUE THREAD

**Issue by ayushanand308** [mrsparkle-70/Emotion-detection-using-JS#44]
Please assign me this issue under JWOC @mrsparkle-70

**Comment by ayushanand308** [comment]
This will take more than a day to implement. Can you please change the difficulty tag for this reason ?

**Comment by mrsparkle-70** [comment]
Ok I will see

**Comment by ayushanand308** [comment]
@mrsparkle-70 That was mistake on my part. So can you elaborate on what you want so that I can implement it as a new feature?

**Comment by ayushanand308** [comment]
@mrsparkle-70  Do you want me to tell similarity between two images uploaded from users computer or similarity  between 2 faces in live video from users camera?

**Comment by mrsparkle-70** [comment]
2nd one

**Comment by ayushanand308** [comment]
Alright!

**Comment by ayushanand308** [comment]
I have implemented the changes. I will be pushing the code soon.

**Comment by ayushanand308** [comment]
I have made a PR. Please review it @mrsparkle-70

**Comment by mrsparkle-70** [comment]
In similarity part what number is showing along the box ?
Is it the percentage the pictures are matching with?

**Comment by ayushanand308** [comment]
@mrsparkle-70  It is the euclidean distance between the two faces which is calculated by the ML model implemented by face-api itself. According to the models, if this euclidean distance is more than 0.6 then the faces are not similar else they are similar.

**Comment by mrsparkle-70** [comment]
I think then you should also show the tag similar/not similar live 
Since I am making this for common people

**Comment by ayushanand308** [comment]
I have added that as well . If faces are similar it shows "faces are similar" and if not then it shows "faces are not similar"

**Comment by ayushanand308** [comment]
Can you please change the issue's difficulty as it was discussed earlier?

**Comment by mrsparkle-70** [comment]
I just read your code
Yes it's done

**Comment by ayushanand308** [comment]
@mrsparkle-70 Have you changed the difficulty tag?

**Comment by mrsparkle-70** [comment]
It was tagged easy right earlier also ?

**Comment by mrsparkle-70** [comment]
Checkout U made pr for issue number 44

I think u confused it with issue number 19

Both are not same

**Comment by ayushanand308** [comment]
Yes I know that I made PR for 44. But as we discussed earlier that it was not a single day task. You can change the difficulty tag if you think the reasoning is apt otherwise its fine. 👍

**Comment by mrsparkle-70** [comment]
Okay I will it to medium
🤗

**Comment by ayushanand308** [comment]
@mrsparkle-70 Thank You!👍

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC. Please assign it to me
