### ISSUE TITLE
No live link to preview

### ISSUE THREAD

**Issue by ritika728** [mrsparkle-70/Emotion-detection-using-JS#45]
Hey @mrsparkle-70 , I would like to open this issue under JWOC. There should be a live link which should be included in the readme of the project. I wish to generate that link using github pages and I'll add it in the readme.

**Comment by mrsparkle-70** [comment]
The link is already generated and I will add it myself.
Try to implement some good features
Take time
Regards
Subham
JWOC 2k23
Mentor

**Comment by ritika728** [comment]
Alright!

**Comment by mrsparkle-70** [comment]
https://mrsparkle-70.github.io/Emotion-detection-using-JS/#

Live Link
