### ISSUE TITLE
Switch(ON/OFF) for Webcam 

### ISSUE THREAD

**Issue by TuhinBanerjee31** [mrsparkle-70/Emotion-detection-using-JS#46]
I want to work on this issue under JWOC.

**Comment by mrsparkle-70** [comment]
You can start
I will assign it to you asap

**Comment by mrsparkle-70** [comment]
I will be expecting some results today

**Comment by pooranjoyb** [comment]
Please Assign me with this issue if there isn't any update. @mrsparkle-70 
Would gladly work into it under JWOC 2023. :)

**Comment by mrsparkle-70** [comment]
If no pr is made till today night u can do this

**Comment by pooranjoyb** [comment]
Sure bhaiyaa. :) @mrsparkle-70
