### ISSUE TITLE
Changing Probability of user's Emotion into Percentage

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#50]
# Reason/Context

## Why we need this improvement?
We need this improvement as the emotion is displayed as a **probability**. But emotions should always be represented in probable **percentage (%)**.

## How will this change help?
It will enhance the overall UI of the webpage, hence giving a better user-experience.

# Description

## How could it be implemented/designed?
This can be achieved by writing some additional code in the `script.js` file.

## Related Screenshots : 

![demo](https://user-images.githubusercontent.com/90945182/221269881-71b85da8-4268-4323-82c6-486118668fbb.png)
## Expected : 

- **Surprised - 64%**
- **Angry - 24%**

### I would like to work on this issue under JWOC 2023. Would be glad if you could assign this issue to me. @mrsparkle-70

**Comment by mrsparkle-70** [comment]
Sure 
U can start 
I will assign
