### ISSUE TITLE
Add an Animated Landing page 

### ISSUE THREAD

**Issue by AK-shat-JAIN** [mrsparkle-70/Emotion-detection-using-JS#53]
The landing page looks very normal
Want to add an animation effect in it such that the text "Emotion Detection" will animate and come like in this website
https://ak-shat-jain.github.io/FoodGenix/
that's also created by me

**Comment by mrsparkle-70** [comment]
Sure
U can start

**Comment by AK-shat-JAIN** [comment]
Thanks I will generate PR by EOD

**Comment by AK-shat-JAIN** [comment]
I have created SVG with background which looks good to me

![image](https://user-images.githubusercontent.com/84455686/221393703-b8bbdee4-dd17-482b-9546-9fd46a3947b7.png)

**Comment by mrsparkle-70** [comment]
U can submit a video recording

**Comment by AK-shat-JAIN** [comment]
ok Give me 1 minute

**Comment by AK-shat-JAIN** [comment]
https://user-images.githubusercontent.com/84455686/221418006-daa89aa7-f82b-405d-a621-456c4681ed06.mp4
