### ISSUE TITLE
[Enhancement] Adding Mobile Responsiveness

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#56]
# Reason/Context

### Why we need this improvement?
In this current version of the page, the mobile version is broken as the UI basically breaks.

### How will this change help?
It will enhance the UI of the webpage, hence giving a better user-experience.

### What changes have to be introduced?
Some significant changes in the UI have to be made in order to make it mobile responsive.

### Will this be a breaking change?
No, it will not break the change.

## Related Screenshot : 
![responsive](https://user-images.githubusercontent.com/90945182/221578127-529ffc9b-192b-4d92-bac6-c2e85a4537d1.png)

## I would like to work in this issue under JWOC 2023. Please assign me. Thanks. @mrsparkle-70

**Comment by mrsparkle-70** [comment]
Sure You can start
I will assign you

**Comment by pooranjoyb** [comment]
Okay sure. :) @mrsparkle-70
