### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by KrunalGupta02** [mrsparkle-70/Emotion-detection-using-JS#6]
Hi, i would like to contribute to this project by providing the dark mode the website for better user experience

**Comment by sagnik3788** [comment]
please assign me

**Comment by vk20july** [comment]
I want to work on this issue under JWOC
sir also this is the correct way to comment on any issue
we have been told in the discord server

**Comment by mrsparkle-70** [comment]
@KrunalGupta02 
U r assigned this

**Comment by vk20july** [comment]
@mrsparkle-70 sir but he commented before 15th feb we were supposed to comment on or after 15th feb

**Comment by KrunalGupta02** [comment]
@mrsparkle-70 I have  made a pr plz check and if changes need plz tell me

**Comment by Shreyan-12345** [comment]
@mrsparkle-70  I want to work under JWOC if the issue is not yet solved
