### ISSUE TITLE
[Enhancement] Making similarity.html Page Responsive.

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#60]
# Reason/Context

### Why we need this improvement?
In this current version of the page, the mobile version is broken as the UI basically breaks.

### How will this change help?
It will enhance the UI of the webpage, hence giving a better user-experience.

### What changes have to be introduced?
Some significant changes in the UI have to be made in order to make it mobile responsive.

### Will this be a breaking change?
No, it will not break the change.

## Related Screenshot : 

![responsive 2](https://user-images.githubusercontent.com/90945182/221864938-7a4d7dc7-bd85-413a-8b80-977bbded255d.png)

## I would like to work in this issue under JWOC 2023. Please assign me. Thanks. @mrsparkle-70 
Also it would be great if you could label it as either `medium` or `hard` as fixing the canvas takes really long. 👍

**Comment by mrsparkle-70** [comment]
Start
