### ISSUE TITLE
Optimize the footer for android devices

### ISSUE THREAD

**Issue by mrsparkle-70** [mrsparkle-70/Emotion-detection-using-JS#70]

**Comment by pooranjoyb** [comment]
I would like to work on this issue under JWOC 2023. Please assign me @mrsparkle-70 😃

**Comment by mrsparkle-70** [comment]
Any update?

**Comment by pooranjoyb** [comment]
Ya bhaiyaa, almost done. Will open a PR by today. @mrsparkle-70
