### ISSUE TITLE
[Feature] Adding a form endpoint in Any Queries section

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#81]
## Description
I would like to add a static endpoint to the `Any Queries. Let us know` part.

## Screenshot : 
![demo18](https://user-images.githubusercontent.com/90945182/223171929-ee1195b5-2bb9-4316-9905-322a3efc7abc.png)

## Outcomes : 
- The queries will be diverted to the user's email address directly through the redirections of the website.
- **No PHP, NodeJS, Express Server or any backend code required**

## Implementation : 
- I would be using a third party website called [FormSubmit](https://formsubmit.co) who will do the work for us.
- We will connect our form to `FormSubmit` endpoint and they'll email us the submissions

### I would like to work on this issue under JWOC 2023. Please assign 😄 @mrsparkle-70

**Comment by mrsparkle-70** [comment]
Sure
Go-ahead with this
