### ISSUE TITLE
Testimonial Responsiveness

### ISSUE THREAD

**Issue by ritika728** [mrsparkle-70/Emotion-detection-using-JS#82]
Hey, I would like to open this issue under JWOC. The testimonial page has responsiveness issue and the pagination buttons are not appearing on small screen size. I would like to improve this

![photo](https://user-images.githubusercontent.com/91181981/223180812-729abff6-1e23-4759-81c4-f631dc1e9085.png)

**Comment by mrsparkle-70** [comment]
Go ahead
