### ISSUE TITLE
Design the upload image page with proper functions

### ISSUE THREAD

**Issue by mrsparkle-70** [mrsparkle-70/Emotion-detection-using-JS#84]

**Comment by thevinitgupta** [comment]
I would love to work on this.

**Comment by mrsparkle-70** [comment]
U can start

**Comment by mrsparkle-70** [comment]
Any update ?

**Comment by pooranjoyb** [comment]
Please Assign me with this issue if there isn't any update.  @mrsparkle-70 
I would love to work on this issue under JWOC 2023.

**Comment by mrsparkle-70** [comment]
Yes you can start
