### ISSUE TITLE
[Feature] Convert the Application to NodeJS App

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#87]
## Outcomes
- We would be able to work on backend part irrespective of the Frontend Condition.
- We will have more authority over our application.
- We would be able to use **Database Management Systems** to store data and information related to the Website for further research purposes.
- Data saving can lead to working on different aspects such as Machine Learning or AI.

### I would like to work on this issue under JWOC 2023. Please Assign me with this issue. @mrsparkle-70

**Comment by mrsparkle-70** [comment]
@pooranjoyb Check the deployment 
Resolve the issues with github pages

**Comment by pooranjoyb** [comment]
> @pooranjoyb Check the deployment 
> Resolve the issues with github pages 

This issue is due to the build command in `vercel` hosting service. This project was configured as a `static website` berfore but now its a `server side application`. We will have to reconfigure `vercel` for the server side application for this repository.

This `vercel-error` can be fixed by you as I don't have credentials for logging into `vercel` to update the new changes with the repo.

I've checked on my side that the application is working perfectly in localhost.

#### I would suggest to remove `vercel` authorization for this Repo during the development period. 
You can reconfigure this once the backend is almost setup.

**Comment by mrsparkle-70** [comment]
Any suggestions for github pages ?

**Comment by pooranjoyb** [comment]
Apparently `github pages` doesn't support server side applications.

It's only made for `Static sites` (without backend)

`Vercel` is a good choice anyways.
Don't worry, during the last days of JWOC 2023. We'll also host this application. :smiley:

**Comment by mrsparkle-70** [comment]
Sure
