### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by ritika728** [mrsparkle-70/Emotion-detection-using-JS#89]
Hey @mrsparkle-70 , I would like to open this issue under JWOC. I wish to add a contact us page:

- a user can submit his information and message to communicate with the admin.
- the page will have same UI as home page & will contain the contact form with illustrations
- the contact form will be validated
- it will be responsive
- I will add it in the menu as well

**Comment by mrsparkle-70** [comment]
Sure
You can start
