### ISSUE TITLE
[Feature] Initiate MongoDB Connection Locally

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#93]
## Description

As the main work of setting up the project to **NodeJS** is finally complete. It is time we start working on the Database.

### Workflow : 
- [x] Install `mongoose` using Node-Package-Manager (npm)
- [x] Setup Directories for the Database.
- [x] Setting Up the Connection on `localhost:3000`
- [x] Defining Schema & Models for the Database
- [x] Setting up Routes for `MongoDB` 
- [x] Hitting endpoints to save data in MongoDB
- [x] Setup `MongoDBCompass` to view data locally.
- [x] Finding to way to dump the data in the repository.

## I would like to work on this issue under JWOC 2023. Please Assign @mrsparkle-70 😄

**Comment by mrsparkle-70** [comment]
Sure
