### ISSUE TITLE
BUG: Add validation of email 

### ISSUE THREAD

**Issue by zugzwang03** [mrsparkle-70/Emotion-detection-using-JS#94]
In the footers, in the query section, the send message button gets submitted without any data in email and issue as well. We can keep a validation check there to avoid spam entries. I can do this under JWOC'23.
![image](https://user-images.githubusercontent.com/95460021/224504702-faaf6736-d8f1-4f3e-bd8b-eae19bae2ce5.png)

**Comment by mrsparkle-70** [comment]
Sure
You can start

**Comment by Prateek556** [comment]
I want to work on this issue under  JWOC

**Comment by mrsparkle-70** [comment]
It's completed
Find or create another issue
