### ISSUE TITLE
Language Translator

### ISSUE THREAD

**Issue by ritika728** [mrsparkle-70/Emotion-detection-using-JS#95]
Hey @mrsparkle-70 , I would like to open this issue under JWOC.  I wish to implement a new feature where:
- User can translate the text into any language with just one click.
- user can select the preferred language from all the possible languages (100+ including hindi) available on Google
- after selecting a specific language, user will be able to :
  - again translate the page by choosing new language
  - showing the original language
  - turn off the translation for that site

I will add this feature in the navbar of all the pages. Kindly assign

**Comment by mrsparkle-70** [comment]
Great feature 
You should start it asap
