### ISSUE TITLE
Dumping MongoDB database into the Repository

### ISSUE THREAD

**Issue by pooranjoyb** [mrsparkle-70/Emotion-detection-using-JS#99]
## Description

We might need to work on the data inside the database, for that we need to make sure that the content inside the database is dumped into the repository. 

## Outcome : 

- A user could dump/restore the database content back into his/her local directory in order to view the database.

I would like to work on this issue under JWOC 2023. Please Assign @mrsparkle-70 👍

**Comment by mrsparkle-70** [comment]
Sure
